### ISSUE TITLE
Whitelist addresses

### ISSUE THREAD

**Issue by Bockiii** [schmich/purify#6]
Hi,

first off, thanks for this docker. It's still the most lightweight dnsmasq/adblocker available in dockerhub, so thanks.

Second: Would it be possible to have a whitelist file? StevenBlacks list also blocks tracking urls that someone might want (s.youtube.com for example). A simple config file with one address per line thats scanned during the update script should be easy to do (I'm just not good in bash).

Thanks in advance

**Comment by schmich** [comment]
Sorry for the delayed reply. It's going to be hard for me to get to this in the near future.

As a workaround, you can fetch Steven Black's list, filter it however you want, and publish the filtered list to GitHub or as a gist. Then, you can use the [custom hosts](https://github.com/schmich/purify#custom-hosts) feature to use your filtered hosts list.

**Comment by Bockiii** [comment]
Hey, no problem :)

Ah okay, thanks for the info, will do something like that.
